project:
  render:
    - main.qmd
    - README.qmd

title: "Computing  an empirical  Fisher information matrix estimate in latent variable models through stochastic approximation"
author:
  - name: Maud Delattre
    corresponding: true
    email: maud.delattre@inrae.fr
    orcid: 0000-0002-3775-9278
    affiliation:
      - name: Université Paris-Saclay, INRAE, MaIAGE, 78350, Jouy-en-Josas, France
  - name: Estelle Kuhn
    email: estelle.kuhn@inrae.fr
    orcid: 0000-0002-1236-8190
    affiliation:
      - name: Université Paris-Saclay, INRAE, MaIAGE, 78350, Jouy-en-Josas, France
date: 11/21/2023
date-modified: last-modified
abstract: >+
  The Fisher information matrix (FIM) is a key quantity in statistics. However its exact computation is often not trivial. In particular in many latent variable models, it is intricated due to the presence of unobserved variables. Several methods have been proposed to approximate the  FIM when it can not be evaluated analytically.  Different  estimates have been considered, in particular moment estimates. However some of them require to compute second derivatives of the complete data log-likelihood which leads to some disadvantages. In this paper, we focus on the empirical Fisher information matrix defined as an empirical estimate of the covariance matrix of the score, which only requires to compute the first derivatives of the log-likelihood. Our contribution consists in presenting a new numerical method to evaluate this empirical Fisher information matrix in latent variable model when the proposed estimate can not be directly analytically evaluated. We propose a stochastic approximation estimation algorithm to compute this estimate as a by-product of the parameter estimate. We evaluate the finite sample size properties of the proposed estimate and the convergence properties of the estimation algorithm through simulation studies. 
keywords: [Model-based standard error, moment estimate, Fisher identity, stochastic approximation algorithm]
citation:
  type: article-journal
  container-title: "Computo"
  doi: "10.57750/r5gx-jk62"
  publisher: "French Statistical Society"
  issn: "2824-7795"
  url: "https://computo-journal.org/published-202311-delattre-fim/"
google-scholar: true
bibliography: references.bib
related-identifiers:
  - relation: IsVersionOf
    type: URL
    identifier: "https://hal.inrae.fr/hal-04347257"
github-user: computorg
repo: "published-202311-delattre-fim"
execute:
  warning: false
  message: false
  keep-md: false
status: published
format:
  computo-html: default
  computo-pdf: default
